full_archive_sandbox:
  account_type: premium
  #endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/xxx.json
  # if you have a bearer token, you can use it below. otherwise, swap the comment marks and use 
  # your app's consumer key/secret - the library will generate and use a bearer token for you. 
  bearer_token: aaabbbccc
  consumer_key: aaabbbccc
  consumer_secret: aaabbbccc

